name: Create Release

on: push
#  push:
#    tags:
#      - '*'

env:
  RELEASE_DIR: ./ShockTheirOsc/bin/Release/net9.0
  BRANCH: main

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - run: dotnet build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip ${{ env.RELEASE_DIR }}
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE.md
            release.zip