name: Create Release

on:
  push:
    tags:
      - '*'

env:
  RELEASE_DIR: ./ShockTheirOsc/bin/Release/net9.0
  BRANCH: main

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - run: dotnet build

      - name: Create Release Zip
        run: |
          cd ./ShockTheirOsc
          ls -la
          cd ${{ env.RELEASE_DIR }}
          zip -qq -r release.zip .
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE.md
            ${{ env.RELEASE_DIR }}/release.zip
        if: github.ref_type == 'tag'
